### PR TITLE
Add dockerfile using graalvm

### PR DESCRIPTION
**Pull request by sycured**
[GraalVM](https://www.graalvm.org/java/) doesn't need any code change to obtain better performance

### CODE REVIEW

**Comment by jonesde** [comment]
While many deployments have a custom Dockerfile, this default one is used by quite a few and I wouldn't want to make this change without some significant testing.

It might be best to start with a discussion on forum.moqui.org, to get feedback and give others a bit of notice and a chance to comment.

An alternative might be to have a separate Dockerfile for GraalVM. One of the reasons the current Dockerfile is in the /docker/simple directory is so that there can be others, like a docker/graalvm directory or something.

**Comment by jonesde** [comment]
While many deployments have a custom Dockerfile, this default one is used by quite a few and I wouldn't want to make this change without some significant testing.

It might be best to start with a discussion on forum.moqui.org, to get feedback and give others a bit of notice and a chance to comment.

An alternative might be to have a separate Dockerfile for GraalVM. One of the reasons the current Dockerfile is in the /docker/simple directory is so that there can be others, like a docker/graalvm directory or something.

**Comment by sycured** [comment]
Modified to follow the alternative so having docker/graalvm directory

**Comment by acetousk** [comment]
@sycured you can now specify an image for the docker file. See: https://github.com/moqui/moqui-framework/pull/544

**Comment by jonesde** [comment]
That's a good point @acetousk 

Your recent changes to support a build script parameter for the base docker image to use will address this need as well, ie make it easy to use GraalVM. IMO that's a better solution to this need.

What do you think @sycured ?

**Comment by sycured** [comment]
Perfect, it's  easier to use custom base image

**Pull request closed without merging**
