### PR TITLE
Integrated Runtime into the monqui

### PR DESCRIPTION
**Pull request by DapperBlondie**

### CODE REVIEW

**Comment by jonesde** [comment]
I don't know if this pull request was meant to be opened, but no we won't be moving moqui-runtime into moqui-framework.

**Comment by DapperBlondie** [comment]
به کیرم :)

**Comment by jonesde** [comment]
Just FYI, this is public and translations are easy (and there are people involved with Moqui who speak Arabic). It sounds like you're having a bad day, or a bad week. If you'd like to discuss this, preferably with more polite language (not that I care, but I only speak for myself), I'd recommend the mailing list or the new forum.

**Comment by DapperBlondie** [comment]
بازم به کیرم

**Pull request closed without merging**
