### PR TITLE
Improved compare method

### PR DESCRIPTION
**Pull request by zhangshifeng**
Fixed exception when create a new example.

### CODE REVIEW

**Comment by jonesde** [comment]
I'd prefer to not add an additional library just to do this. What is the issue you saw or more generally the reason for this change?

**Comment by zhangshifeng** [comment]
Go to https://demo.moqui.org/apps/example/Example/EditExample, click 'New Example' button, you will see an exception.

**Comment by zhangshifeng** [comment]
Updated.
Apache commons-lang was removed.

**Comment by jonesde** [comment]
Thank you, I see the issue that the EditExample screen uses this method with a null value which used to be supported and wasn't after the move from Groovy to Java for this method so adding back compare support for a null field is needed. Your latest changes look good but I already had some slightly simpler ones (not as good as yours in some ways, but simpler) so I committed those.

**Pull request closed without merging**
